### ISSUE TITLE
plugin name length will prevent use of tables in future.

### ISSUE THREAD

**Issue by danmarsden** [pmaneggia/moodle-block_availdep#1]
Your frankenstyle plugin name is very long (block_availability_dependencies) - Moodle database tables have a limit of 28 characters and any tables you implement inside your plugin must be prefixed with the frankenstyle name - your name is 32 characters which means that you would not be able to implement any tables within this plugin in future.

Feel free to close this if you do not think this will be an issue, and you can't see a need to implement any tables within the plugin, but I mention this now, because there is no easy way to "rename" a plugin once it's installed on a site and you can't rename plugins in the plugins db either, you have to make a new plugin submission.

thanks!

**Comment by pmaneggia** [comment]
Many thanks for this advise. Even if right now I do not expect to need a table, I still prefer not to be in the condition of needing one and not being able to add it. I fixed this now (https://github.com/pmaneggia/moodle-block_availdep/commit/4758a92531a7fea1fb55d6341b727fed2061850f). I will come back and ask how do I change my submission once the other changes are ready.
