### ISSUE TITLE
consider adding github action support

### ISSUE THREAD

**Issue by danmarsden** [pmaneggia/moodle-block_availdep#2]
Some of the tests run by the Moodle.org plugins db can be run via github actions on each commit in your github repo. Enabling this helps you to make sure future changes to your plugin will continue to follow the guidelines.

the short version - grab this file:
https://github.com/moodlehq/moodle-plugin-ci/blob/master/gha.dist.yml
rename it as ci.yml and put into the directory .github/workflows within tyour project eg:
https://github.com/danmarsden/moodle-mod_attendance/blob/MOODLE_311_STABLE/.github/workflows/ci.yml

then on every commit you make to github it will fire off a request to run the tests and will give you traffic lights beside each commit and generate a report.

**Comment by pmaneggia** [comment]
Thanks for the advise. It took a bit of time to get this done. At the moment I have one last bit of probem that I am not managing to solve: the grunt task fails with `File is stale and needs to be rebuilt: amd/build/visualiseDependencies.min.js.map amd/build/visualiseDependencies.min.js
Error: Process completed with exit code 1.`

**Comment by pmaneggia** [comment]
The problem seems to be linked with the fact that at the moment I am on a Moodle 4.0 instead of 3.11 when running grunt.
