### ISSUE TITLE
embedding of d3 uses incorrect path

### ISSUE THREAD

**Issue by danmarsden** [pmaneggia/moodle-block_availdep#4]
when a moodle site is hosted on a path that is not the root eg:
www.example.com/moodle

the d3 include tries to use the path
www.example.com/blocks/availability_dependencies/thirdparty/d3.min.js
instead of:
www.example.com/mooodle/blocks/availability_dependencies/thirdparty/d3.min.js

probably needs to be using the var $CFG->wwwroot in the path.

**Comment by pmaneggia** [comment]
This should now be fixed
